{
    "totalCount": 1,
    "data": [
        {
            "_id": "67ee823296c4a8da2c01603e",
            "orderNo": "0000009592",
            "customerCode": "0660237605",
            "directCheckout": true,
            "createdBy": "CELLO_JCA",
            "evTotalTds": "0.00",
            "evTotalTcs": "2.00",
            "orderType": "",
            "totalQuantity": "8",
            "totalTax": "277.04",
            "totalDiscount": "0.00",
            "totalAmount": "4058",
            "orderStatus": "PAR",
            "paymentStatus": "COM",
            "orderFulfillmentStatus": "N",
            "JPSite": "I001",
            "etpOrder": "B",
            "deliveryPlant": "I001",
            "handPickup": "",
            "paymentRetryCount": 2,
            "eWalletTransferRetryCount": 2,
            "pgiQuantity": "1",
            "details": [
                {
                    "orderType": "Jio Bharat TP Sales - ZBHB",
                    "articleCode": "000000000910000154",
                    "minQuantity": "2.000",
                    "orderQuantity": "2",
                    "deliveredQuantity": "0",
                    "UoM": "EA",
                    "grossAmt": "1941.00",
                    "grossTax": "0.0000",
                    "evTds": "0.00",
                    "evTcs": "0.00",
                    "grossDiscount": "0.00",
                    "netAmount": "1941.00",
                    "pricePerQty": "822.43",
                    "pgiStatus": " ",
                    "pgiQuantity": "0",
                    "shortCloseQty": "0",
                    "fulfillmentStatus": "N",
                    "changedByUser": "",
                    "etpOrder": "D",
                    "article": {
                        "orderType": "ZBHB",
                        "orderDescription": "B4",
                        "salesRegion": "MH",
                        "priceGroup": "B4",
                        "region2": "MH",
                        "articleCode": "000000000910000154",
                        "parentArticle": "X",
                        "articleDescriptionUI": "Jiobharatparentarticle",
                        "articleDescriptionSAP": "Jiobharatparentarticle",
                        "articleUOM": "EA",
                        "minQuantity": "1",
                        "maxQuantity": "10",
                        "maxQuantityPerDay": "200",
                        "maxQuantityPerWeek": "200",
                        "maxQuantityPerMonth": "800",
                        "pullPushIndicator": "PS",
                        "returnIndicator": "R",
                        "lotSize": "1",
                        "createdLoc": "MH",
                        "changedLoc": "MH",
                        "createdBy": "",
                        "changedBy": "P55015429",
                        "serialNoIndicator": "S",
                        "aadChangeDeleteIndicator": "I",
                        "pricing": [
                            {
                                "priceCondition": "ZMR1",
                                "salesOrg": "9008",
                                "disChannel": "51",
                                "salesDocument": "ZBHB",
                                "basicPrice": "100",
                                "discount1": "",
                                "discountUnit1": "",
                                "discount2": "",
                                "discountUnit2": "",
                                "discount3": "",
                                "discountUnit3": "",
                                "discount4": "",
                                "discountUnit4": "",
                                "pricePerUnit": "100",
                                "currency": "INR",
                                "startFrom": "2025-02-10T00:00:00.000Z",
                                "dateUpto": "9999-02-09T00:00:00.000Z",
                                "aadChangeDeleteIndicator": "I",
                                "_id": "67ee840bb75d7eddb2343785"
                            }
                        ]
                    },
                    "_id": "67ee840bb75d7eddb2343784"
                },
                {
                    "orderType": "Jio Bharat - ZBHA",
                    "articleCode": "000000000910000155",
                    "minQuantity": "2.000",
                    "orderQuantity": "2",
                    "deliveredQuantity": "1",
                    "UoM": "EA",
                    "grossAmt": "30.51",
                    "grossTax": "5.4900",
                    "evTds": "0.00",
                    "evTcs": "0.00",
                    "grossDiscount": "0.00",
                    "netAmount": "36.00",
                    "pricePerQty": "15.26",
                    "pgiStatus": "F",
                    "pgiQuantity": "1",
                    "shortCloseQty": "1",
                    "fulfillmentStatus": "Y",
                    "changedByUser": "",
                    "etpOrder": "D",
                    "article": {
                        "orderType": "ZBHA",
                        "orderDescription": "JIOBHARATSale",
                        "salesRegion": "MH",
                        "priceGroup": "EE",
                        "region2": "MH",
                        "articleCode": "000000000910000155",
                        "parentArticle": "",
                        "articleDescriptionUI": "OrderZIFC",
                        "articleDescriptionSAP": "OrderZIFC",
                        "articleUOM": "EA",
                        "minQuantity": "1",
                        "maxQuantity": "10",
                        "maxQuantityPerDay": "20",
                        "maxQuantityPerWeek": "200",
                        "maxQuantityPerMonth": "800",
                        "pullPushIndicator": "PS",
                        "returnIndicator": "R",
                        "lotSize": "1",
                        "createdLoc": "MH",
                        "changedLoc": "MH",
                        "createdBy": "P55015429",
                        "changedBy": "",
                        "serialNoIndicator": "",
                        "aadChangeDeleteIndicator": "I",
                        "pricing": [
                            {
                                "priceCondition": "ZMR1",
                                "salesOrg": "9008",
                                "disChannel": "51",
                                "salesDocument": "ZBHA",
                                "basicPrice": "100",
                                "discount1": "",
                                "discountUnit1": "",
                                "discount2": "",
                                "discountUnit2": "",
                                "discount3": "",
                                "discountUnit3": "",
                                "discount4": "",
                                "discountUnit4": "",
                                "pricePerUnit": "100",
                                "currency": "INR",
                                "startFrom": "2024-12-03T00:00:00.000Z",
                                "dateUpto": "9999-03-30T00:00:00.000Z",
                                "aadChangeDeleteIndicator": "I",
                                "_id": "67ee840bb75d7eddb2343787"
                            }
                        ]
                    },
                    "_id": "67ee840bb75d7eddb2343786",
                    "childMaterials": [],
                    "shortCloseCode": "110 - Customer Request",
                    "shortCloseDate": "2025-04-03T12:55:44.848Z",
                    "shortCloseReason": "closed",
                    "shortCloseStatus": "U",
                    "billingStatus": "S",
                    "pgiDocNo": "4900028779",
                    "undeliveredQuantity": "1"
                },
                {
                    "orderType": "Jio Bharat - ZBHA",
                    "articleCode": "000000000910000130",
                    "minQuantity": "2.000",
                    "orderQuantity": "2",
                    "deliveredQuantity": "0",
                    "UoM": "EA",
                    "grossAmt": "1508.45",
                    "grossTax": "271.5500",
                    "evTds": "0.00",
                    "evTcs": "2.00",
                    "grossDiscount": "0.00",
                    "netAmount": "1782.00",
                    "pricePerQty": "754.23",
                    "pgiStatus": " ",
                    "pgiQuantity": "0",
                    "shortCloseQty": "0",
                    "fulfillmentStatus": "N",
                    "changedByUser": "",
                    "etpOrder": "D",
                    "article": {
                        "orderType": "ZBHA",
                        "orderDescription": "JIOBHARATSale",
                        "salesRegion": "MH",
                        "priceGroup": "B4",
                        "region2": "MH",
                        "articleCode": "000000000910000130",
                        "parentArticle": "X",
                        "articleDescriptionUI": "Handset",
                        "articleDescriptionSAP": "Handset",
                        "articleUOM": "EA",
                        "minQuantity": "1",
                        "maxQuantity": "10",
                        "maxQuantityPerDay": "50",
                        "maxQuantityPerWeek": "100",
                        "maxQuantityPerMonth": "500",
                        "pullPushIndicator": "PS",
                        "returnIndicator": "R",
                        "lotSize": "1",
                        "createdLoc": "MH",
                        "changedLoc": "MH",
                        "createdBy": "",
                        "changedBy": "P55015429",
                        "serialNoIndicator": "S",
                        "aadChangeDeleteIndicator": "I",
                        "pricing": [
                            {
                                "priceCondition": "ZMR1",
                                "salesOrg": "9008",
                                "disChannel": "51",
                                "salesDocument": "ZBHA",
                                "basicPrice": "791.28",
                                "discount1": "",
                                "discountUnit1": "",
                                "discount2": "",
                                "discountUnit2": "",
                                "discount3": "",
                                "discountUnit3": "",
                                "discount4": "",
                                "discountUnit4": "",
                                "pricePerUnit": "933.71",
                                "currency": "INR",
                                "startFrom": "2024-07-12T00:00:00.000Z",
                                "dateUpto": "2050-07-12T00:00:00.000Z",
                                "aadChangeDeleteIndicator": "I",
                                "_id": "67ee840bb75d7eddb2343789"
                            }
                        ]
                    },
                    "_id": "67ee840bb75d7eddb2343788"
                },
                {
                    "orderType": "SIM - ZJTP",
                    "articleCode": "000000000400000001",
                    "minQuantity": "2.000",
                    "orderQuantity": "2",
                    "deliveredQuantity": "0",
                    "UoM": "",
                    "grossAmt": "100.00",
                    "grossTax": "0.0000",
                    "evTds": "0.00",
                    "evTcs": "0.00",
                    "grossDiscount": "0.00",
                    "netAmount": "100.00",
                    "pricePerQty": "0.00",
                    "pgiStatus": " ",
                    "pgiQuantity": "0",
                    "shortCloseQty": "0",
                    "fulfillmentStatus": "N",
                    "changedByUser": "",
                    "etpOrder": "D",
                    "article": {
                        "orderType": "ZJTP",
                        "orderDescription": "",
                        "salesRegion": "MH",
                        "priceGroup": "EE",
                        "region2": "MH",
                        "articleCode": "000000000400000001",
                        "parentArticle": "",
                        "articleDescriptionUI": "SIM",
                        "articleDescriptionSAP": "SIM",
                        "articleUOM": "EA",
                        "minQuantity": "1",
                        "maxQuantity": "10",
                        "maxQuantityPerDay": "100",
                        "maxQuantityPerWeek": "400",
                        "maxQuantityPerMonth": "1000",
                        "pullPushIndicator": "PS",
                        "returnIndicator": "R",
                        "lotSize": "1",
                        "createdLoc": "MH",
                        "changedLoc": "MH",
                        "createdBy": "P55015429",
                        "changedBy": "",
                        "serialNoIndicator": "S",
                        "aadChangeDeleteIndicator": "I",
                        "pricing": [
                            {
                                "priceCondition": "ZMR1",
                                "salesOrg": "9008",
                                "disChannel": "51",
                                "salesDocument": "ZJTP",
                                "basicPrice": "100",
                                "discount1": "",
                                "discountUnit1": "",
                                "discount2": "",
                                "discountUnit2": "",
                                "discount3": "",
                                "discountUnit3": "",
                                "discount4": "",
                                "discountUnit4": "",
                                "pricePerUnit": "100",
                                "currency": "INR",
                                "startFrom": "2024-08-22T00:00:00.000Z",
                                "dateUpto": "9999-03-30T00:00:00.000Z",
                                "aadChangeDeleteIndicator": "I",
                                "_id": "67ee840bb75d7eddb234378b"
                            }
                        ]
                    },
                    "_id": "67ee840bb75d7eddb234378a",
                    "shortCloseCode": "110 - Customer Request",
                    "shortCloseDate": "2025-04-03T12:52:21.692Z",
                    "shortCloseReason": "closed",
                    "shortCloseStatus": "N",
                    "shortCloseRemark": "reject"
                },
                {
                    "orderType": "ZETP",
                    "articleCode": "000000000490000029",
                    "orderQuantity": "207.000",
                    "deliveredQuantity": "0",
                    "UoM": "EA",
                    "grossAmt": "199.000",
                    "grossTax": "",
                    "grossDiscount": "",
                    "netAmount": "199.000",
                    "pricePerQty": "1",
                    "pgiStatus": " ",
                    "pgiQuantity": "0",
                    "shortCloseQty": "0",
                    "fulfillmentStatus": "Y",
                    "changedByUser": "",
                    "etpOrder": "E",
                    "article": {
                        "orderType": "ZETP",
                        "orderDescription": "EWallet",
                        "salesRegion": "",
                        "priceGroup": "",
                        "region2": "MH",
                        "articleCode": "000000000490000029",
                        "parentArticle": "",
                        "articleUOM": "EA",
                        "minQuantity": "",
                        "maxQuantity": "",
                        "maxQuantityPerDay": "",
                        "maxQuantityPerWeek": "",
                        "maxQuantityPerMonth": "",
                        "pullPushIndicator": "PL",
                        "returnIndicator": "R",
                        "lotSize": "",
                        "createdLoc": "",
                        "changedLoc": "",
                        "createdBy": "",
                        "changedBy": "",
                        "aadChangeDeleteIndicator": "I",
                        "pricing": [
                            {
                                "priceCondition": "",
                                "salesOrg": "",
                                "disChannel": "",
                                "salesDocument": "ZETP",
                                "salesRegion": "",
                                "priceGroup": "",
                                "articleCode": "000000000490000029",
                                "basicPrice": "199.000",
                                "discount1": "",
                                "discountUnit1": "",
                                "discount2": "",
                                "discountUnit2": "",
                                "discount3": "",
                                "discount4": "",
                                "discountUnit4": "",
                                "pricePerUnit": "1",
                                "currency": "INR",
                                "startFrom": null,
                                "dateUpto": null,
                                "aadChangeDeleteIndicator": "I",
                                "_id": "67ee841a826d9f3776a92d04"
                            }
                        ]
                    },
                    "_id": "67ee841a826d9f3776a92d03",
                    "orderNumberSAP": "0000005074",
                    "transId": "0090018422"
                }
            ],
            "paymentDetails": [
                {
                    "creditControlArea": "RREL",
                    "item": "1",
                    "type": "P",
                    "paymentType": "J",
                    "totalAmount": "4058",
                    "amount": "199",
                    "transStatus": "S",
                    "transReference": "0000009592",
                    "MoP": "JPG",
                    "_id": "67ee842d96c4a8da2c016115",
                    "MoPCode": "189",
                    "MoPPaymentDesc": "Net Banking",
                    "instrumentDate": "2025-04-03T18:21:07",
                    "instrumentReference": "20250403011670000114619764577974045",
                    "accountingDocument": "1050000021"
                },
                {
                    "creditControlArea": "CREL",
                    "item": "2",
                    "type": "P",
                    "paymentType": "C",
                    "totalAmount": "4058",
                    "amount": "3859",
                    "transStatus": "",
                    "transReference": "0000009592",
                    "MoP": "",
                    "_id": "67ee842d96c4a8da2c016116",
                    "accountingDocument": "1050000021"
                }
            ],
            "__v": 1,
            "orderCombinedStatus": "DCWJ",
            "createdAt": "2025-04-03T12:50:53.511Z",
            "updatedAt": "2025-04-03T12:55:45.775Z",
            "redisStatus": "C",
            "paymentAccountingStatus": "PAS",
            "walletTransferStatus": "COM",
            "userId": "0682046886"
        }
    ]
}
